// This file defines the simulated participant used by jsPsych.simulate().
// It does not choose adaptive designs or update the posterior; the Stan controller
// does that. The simulated participant is MODEL-AGNOSTIC: it draws responses from
// the same likelihood the ADO engine and Stan use, via the model adapter's
// responseProb. Adding a new model requires no changes here.

/**
 * @typedef {Object} DelayDiscountingDesign
 * @property {number} r_ss - Smaller-sooner reward.
 * @property {number} t_ss - Smaller-sooner delay.
 * @property {number} r_ll - Larger-later reward.
 * @property {number} t_ll - Larger-later delay.
 */

/**
 * @typedef {Object} ModelAdapter
 * @property {Function} responseProb - (design, params) => P(response = 1 = LL).
 * @property {Function} [subjectiveValues] - Optional (design, params) => model-specific
 *   diagnostics, e.g. {v_ss, v_ll}, recorded as sim_* audit fields.
 */

const SS_RESPONSE = 0;
const LL_RESPONSE = 1;

/**
 * Create a deterministic random number generator for reproducible simulations.
 *
 * @param {number} seed - Integer seed for the generator.
 * @returns {Function} Function that returns numbers in [0, 1).
 */
function createSeededRng(seed) {
  let state = Math.floor(Number(seed)) % 2147483647;
  if (state <= 0) {
    state += 2147483646;
  }

  return function() {
    state = state * 16807 % 2147483647;
    return (state - 1) / 2147483646;
  };
}

/**
 * Generate jsPsych simulation data for one choice trial under a model adapter.
 *
 * The response is drawn from model.responseProb — the exact likelihood used by the
 * MI engine and the Stan model — so the data is generated by the same model that
 * is fit. The data-generating parameters are recorded generically as sim_<param>.
 *
 * @param {DelayDiscountingDesign} design - Current SS/LL offer shown on screen.
 * @param {Object} simulation_config - Delay-discounting simulation settings.
 * @param {Object} simulation_config.params - Data-generating parameters (e.g. {k, tau}).
 * @param {Object} simulation_config.rt - Simulated response times.
 * @param {number} simulation_config.rt.choice - Simulated choice-trial RT.
 * @param {Function} rng - Seeded random number generator.
 * @param {ModelAdapter} model - Active model adapter.
 * @returns {Object} jsPsych response/RT plus sim_* audit fields.
 */
function simulateDelayDiscountingChoice(design, simulation_config, rng, model) {
  const params = simulation_config.params;
  const p_ll = model.responseProb(design, params);
  const draw = rng();
  const response = draw < p_ll ? LL_RESPONSE : SS_RESPONSE;

  const data = {
    // jsPsych simulation fields. response is the button index to click.
    response,
    rt: simulation_config.rt.choice,

    // Audit fields saved into the jsPsych data row for validation/recovery.
    sim_p_ll: p_ll,
    sim_draw: draw,
  };

  // Record the data-generating parameters generically (sim_k, sim_tau, ...).
  for (const [name, value] of Object.entries(params)) {
    data["sim_" + name] = Number(value);
  }

  // Optional model-specific diagnostics (e.g. subjective values for DD models),
  // recorded generically as sim_<name> for whatever fields the model returns.
  if (typeof model.subjectiveValues === "function") {
    for (const [name, value] of Object.entries(model.subjectiveValues(design, params))) {
      data["sim_" + name] = value;
    }
  }

  return data;
}

export {
  createSeededRng,
  simulateDelayDiscountingChoice,
};
