// This file defines the simulated participant used by jsPsych.simulate().
// It does not choose adaptive designs or update the posterior; the Stan controller
// does that. The simulated participant is MODEL-AGNOSTIC: it draws responses from
// the same likelihood the ADO engine and Stan use, via the model adapter's
// responseProb/responseProbs. Adding a new model requires no changes here.

import {
  getResponseProbsFunction,
  validateResponseProbs,
} from "./mi_engine.js";

/**
 * @typedef {Object} DelayDiscountingDesign
 * @property {number} r_ss - Smaller-sooner reward.
 * @property {number} t_ss - Smaller-sooner delay.
 * @property {number} r_ll - Larger-later reward.
 * @property {number} t_ll - Larger-later delay.
 */

/**
 * @typedef {Object} ModelAdapter
 * @property {Function} [responseProb] - (design, params) => P(response = 1).
 * @property {Function} [responseProbs] - (design, params) => [p0, p1, ...].
 * @property {Function} [subjectiveValues] - Optional (design, params) => model-specific
 *   diagnostics, e.g. {v_ss, v_ll}, recorded as sim_* audit fields.
 * @property {Function} [simulationData] - Optional (design, params, probs, response)
 *   => extra sim_* audit fields.
 */

/**
 * Create a deterministic random number generator for reproducible simulations.
 *
 * @param {number} seed - Integer seed for the generator.
 * @returns {Function} Function that returns numbers in [0, 1).
 */
function createSeededRng(seed) {
  let state = Math.floor(Number(seed)) % 2147483647;
  if (state <= 0) {
    state += 2147483646;
  }

  return function() {
    state = state * 16807 % 2147483647;
    return (state - 1) / 2147483646;
  };
}

function sampleResponse(probs, rng) {
  const draw = rng();
  let response = probs.length - 1;
  let cumulative = 0;
  for (let i = 0; i < probs.length; i++) {
    cumulative += probs[i];
    if (draw < cumulative) {
      response = i;
      break;
    }
  }
  return { response, draw };
}

function responseLabelSlug(label, index) {
  if (label == null) {
    return String(index);
  }
  const slug = String(label).toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return slug || String(index);
}

/**
 * Generate jsPsych simulation data for one categorical choice trial.
 *
 * @param {Object} design - Current design shown on screen.
 * @param {Object} simulation_config - Simulation settings with params and rt.
 * @param {Function} rng - Seeded random number generator.
 * @param {ModelAdapter} model - Active model adapter.
 * @param {Object} [opts]
 * @param {Object} [opts.response_labels] - Response labels keyed by choice index.
 * @returns {Object} jsPsych response/RT plus sim_* audit fields.
 */
function simulateCategoricalChoice(design, simulation_config, rng, model, opts = {}) {
  const params = simulation_config.params;
  const responseProbs = getResponseProbsFunction(model);
  const probs = validateResponseProbs(responseProbs(design, params), "simulateCategoricalChoice");
  const { response, draw } = sampleResponse(probs, rng);

  const data = {
    response,
    rt: simulation_config.rt.choice,
    sim_draw: draw,
  };

  for (let i = 0; i < probs.length; i++) {
    const label = opts.response_labels ? opts.response_labels[i] : null;
    data["sim_p_" + responseLabelSlug(label, i)] = probs[i];
  }
  for (const [name, value] of Object.entries(params)) {
    data["sim_" + name] = Number(value);
  }
  if (typeof model.simulationData === "function") {
    Object.assign(data, model.simulationData(design, params, probs, response));
  }
  return data;
}

/**
 * Generate jsPsych simulation data for one choice trial under a model adapter.
 *
 * The response is drawn from model.responseProb — the exact likelihood used by the
 * MI engine and the Stan model — so the data is generated by the same model that
 * is fit. The data-generating parameters are recorded generically as sim_<param>.
 *
 * @param {DelayDiscountingDesign} design - Current SS/LL offer shown on screen.
 * @param {Object} simulation_config - Delay-discounting simulation settings.
 * @param {Object} simulation_config.params - Data-generating parameters (e.g. {k, tau}).
 * @param {Object} simulation_config.rt - Simulated response times.
 * @param {number} simulation_config.rt.choice - Simulated choice-trial RT.
 * @param {Function} rng - Seeded random number generator.
 * @param {ModelAdapter} model - Active model adapter.
 * @returns {Object} jsPsych response/RT plus sim_* audit fields.
 */
function simulateDelayDiscountingChoice(design, simulation_config, rng, model) {
  const data = simulateCategoricalChoice(design, simulation_config, rng, model, {
    response_labels: { 0: "SS", 1: "LL" },
  });
  const params = simulation_config.params;

  // Optional model-specific diagnostics (e.g. subjective values for DD models),
  // recorded generically as sim_<name> for whatever fields the model returns.
  if (typeof model.subjectiveValues === "function") {
    for (const [name, value] of Object.entries(model.subjectiveValues(design, params))) {
      data["sim_" + name] = value;
    }
  }

  return data;
}

export {
  createSeededRng,
  simulateCategoricalChoice,
  simulateDelayDiscountingChoice,
};
