// This file defines the simulated participant used by jsPsych.simulate().
// It does not choose adaptive designs or update the posterior; the Stan controller
// does that. The simulated participant draws responses from the same likelihood the
// ADO engine and Stan use: discrete models via the adapter's responseProb/responseProbs
// (simulateCategoricalChoice), continuous models via the adapter's responseSampler
// (simulateContinuousResponse). Each demo wires the matching simulator for its model.

import { getResponseProbsFunction, validateResponseProbs } from "./mi_engine.js";

/**
 * @typedef {Object} ModelAdapter
 * @property {Function} [responseProb] - (design, params) => P(response = 1).
 * @property {Function} [responseProbs] - (design, params) => [p0, p1, ...].
 * @property {Function} [subjectiveValues] - Optional (design, params) => model-specific
 *   diagnostics recorded as sim_* audit fields (e.g. a discounting model's subjective values).
 * @property {Function} [simulationData] - Optional (design, params, probs, response)
 *   => extra sim_* audit fields.
 */

/**
 * Create a deterministic random number generator for reproducible simulations.
 *
 * @param {number} seed - Integer seed for the generator.
 * @returns {Function} Function that returns numbers in [0, 1).
 */
function createSeededRng(seed) {
  let state = Math.floor(Number(seed)) % 2147483647;
  if (state <= 0) {
    state += 2147483646;
  }

  return function () {
    state = (state * 16807) % 2147483647;
    return (state - 1) / 2147483646;
  };
}

function sampleResponse(probs, rng) {
  const draw = rng();
  let response = probs.length - 1;
  let cumulative = 0;
  for (let i = 0; i < probs.length; i++) {
    cumulative += probs[i];
    if (draw < cumulative) {
      response = i;
      break;
    }
  }
  return { response, draw };
}

function responseLabelSlug(label, index) {
  if (label == null) {
    return String(index);
  }
  const slug = String(label)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return slug || String(index);
}

/**
 * Generate jsPsych simulation data for one discrete (binary or categorical) choice trial.
 *
 * Binary is just the 2-category case, so this is the single discrete simulator. The
 * response is drawn from the model's own likelihood (the exact one the MI engine and Stan
 * use). Two optional model hooks contribute sim_* audit fields:
 * simulationData(design, params, probs, response) for response-conditioned diagnostics,
 * and subjectiveValues(design, params) for design-level diagnostics (e.g. a discounting
 * model's subjective values).
 *
 * @param {Object} design - Current design shown on screen.
 * @param {Object} simulation_config - Simulation settings with params and rt.
 * @param {Function} rng - Seeded random number generator.
 * @param {ModelAdapter} model - Active model adapter.
 * @param {Object} [opts]
 * @param {Object} [opts.response_labels] - Response labels keyed by choice index, used to
 *   name the sim_p_<label> audit fields (defaults to numeric indices).
 * @returns {Object} jsPsych response/RT plus sim_* audit fields.
 */
function simulateCategoricalChoice(design, simulation_config, rng, model, opts = {}) {
  const params = simulation_config.params;
  const responseProbs = getResponseProbsFunction(model);
  const probs = validateResponseProbs(responseProbs(design, params), "simulateCategoricalChoice");
  const { response, draw } = sampleResponse(probs, rng);

  const data = {
    response,
    rt: simulation_config.rt.choice,
    sim_draw: draw,
  };

  for (let i = 0; i < probs.length; i++) {
    const label = opts.response_labels ? opts.response_labels[i] : null;
    data["sim_p_" + responseLabelSlug(label, i)] = probs[i];
  }
  for (const [name, value] of Object.entries(params)) {
    data["sim_" + name] = Number(value);
  }
  if (typeof model.simulationData === "function") {
    Object.assign(data, model.simulationData(design, params, probs, response));
  }
  // Optional design-level diagnostics (e.g. a discounting model's subjective values),
  // recorded as sim_<name>; runs for any discrete model that supplies the hook.
  if (typeof model.subjectiveValues === "function") {
    for (const [name, value] of Object.entries(model.subjectiveValues(design, params))) {
      data["sim_" + name] = value;
    }
  }
  return data;
}

/**
 * Generate jsPsych simulation data for one CONTINUOUS-response trial.
 *
 * Draws a real-valued response from model.responseSampler(design, params, rng) — the
 * model's own data-generating density, the same likelihood the engine integrates and
 * Stan fits — so the simulated participant is generated by the model being fit.
 *
 * @param {Object} design - Current design shown on screen.
 * @param {Object} simulation_config - Simulation settings with params and rt.
 * @param {Function} rng - Seeded random number generator.
 * @param {ModelAdapter} model - Active model adapter (needs responseSampler).
 * @returns {Object} jsPsych response/RT plus sim_* audit fields.
 */
function simulateContinuousResponse(design, simulation_config, rng, model) {
  if (typeof model.responseSampler !== "function") {
    throw new Error(
      "simulateContinuousResponse: a continuous model must provide responseSampler(design, params, rng).",
    );
  }
  const params = simulation_config.params;
  const response = Number(model.responseSampler(design, params, rng));
  if (!Number.isFinite(response)) {
    throw new Error("simulateContinuousResponse: responseSampler must return a finite number.");
  }

  const data = {
    response,
    rt: simulation_config.rt.choice,
    sim_response: response,
  };
  for (const [name, value] of Object.entries(params)) {
    data["sim_" + name] = Number(value);
  }
  if (typeof model.simulationData === "function") {
    Object.assign(data, model.simulationData(design, params, response));
  }
  return data;
}

export { createSeededRng, simulateCategoricalChoice, simulateContinuousResponse };
